### ISSUE TITLE
Model Loading Error

### ISSUE THREAD

**Issue by Ashishkumar-hub** [WeirongChen/DeepEdge#1]
![image](https://user-images.githubusercontent.com/55132850/159733545-ccc6ffc5-096b-4d2a-9571-9e763669daeb.png)

_Getting an incorrect model error while loading the model i have downloaded both the models and i tried loading them both i am using matlabr2019a currently is it because of that?

**Comment by WeirongChen** [comment]
Hi, 
You need:
     - MATLAB R2021a or newer
     - Deep Learning Toolbox
     - Image Processing toolbox 
     - Computer Vision toolbox 
 Let me know if it works.  Thanks!

**Comment by Ashishkumar-hub** [comment]
> Hi, You need: - MATLAB R2021a or newer - Deep Learning Toolbox - Image Processing toolbox - Computer Vision toolbox Let me know if it works. Thanks!

ok thank you will try it with newer Matlab version
