### ISSUE TITLE
Could I get a smooth contour rather than series of points?

### ISSUE THREAD

**Issue by zelato** [WeirongChen/DeepEdge#5]

**Comment by WeirongChen** [comment]
Yes, when you export the results to a MATLAB structure in .mat format, you can find a field 'XY' for a 100-point smoothed contour.

**Comment by zelato** [comment]
Excuse me, how could I see the 100-point contour on the ultrasound frame to check whether it fits well or not? I can only see the anchor when I try "load contour"
