### ISSUE TITLE
Question re: make_snake

### ISSUE THREAD

**Issue by jahyki** [WeirongChen/DeepEdge#9]
Hello

I am hoping to ask for some help with running DeepEdge.

In our lab, we have been able to run DeepEdge on Intel-run Windows laptop and macOS-run iMac. But I don't seem to be able to get it working on my MacBook Pro. My MacBook pro is 14-inch, Nov 2023 model and runs on Apple M3 chip. The current macOS is Sonoma version 14.3.1.

I have tried running it on both MATLAB_R2023b and MATLAB_R2024a versions. I have tried both DpEdg_General_128_25MAR2023 and DpEdg_General_64_augm_30MAR2023. I have also tried both make_snake from SLURP repository (both for MAC and for newer MAC, as per your recommendation in the README file).

I can load DeepEdge on MATLAB. I can also load videos only, and videos+textgrid and videos+contours+textgrid from your example files and from our own data.

However, when I click "Apply to current frame" or "Track thru Frames in this file" or "Track thru Files in list (auto-save on)",
<img width="899" alt="Screenshot 2024-05-05 at 2 06 51 pm" src="https://github.com/WeirongChen/DeepEdge/assets/98289234/61c2c9cc-0f2a-483c-ac17-bad5629d9d47">

I can this error message on MATLAB

----------
Unrecognized function or variable 'make_snake'.

Error in slurp_snake (line 37)
    [xy, energy] = make_snake(transIm, transEgrad, pts, DeltaArr,  BandPenalty, Alpha, Lambda1, UseBand);

Error in DeepEdge/detectOneFrame (line 1317)
                    [anchors, snakeEnergy]=slurp_snake(im_cropped , anchors, [], nPt, sigma, Delta, BandPenalty, Alpha, Lambda1, ROI, [], UseBand);

Error in DeepEdge/TrackThruAllFrames (line 2163)
                    [anchors, energy, xy, nnMask, success] = detectOneFrame(app, im, method, anchors);

Error in DeepEdge/StartTracking (line 3812)
             [status, EndFrame] = TrackThruAllFrames(app, StartFrame, EndFrame, method);

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 172)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62)
            newCallback = @(source, event)executeCallback(ams, ...
 
Error using appdesservices.internal.interfaces.model.AbstractModel/executeUserCallback (line 310)
Error while evaluating StateButton PrivateValueChangedFcn.
----------

I get this error message using both MALAB versions, both DeepEdge versions and both make_snake versions. I gather that the issue is with 'make_snake' file. I am hoping to ask whether I could get some help resolving this issue. Would you have any solution to this issue? Again, we have been able to run DeepEdge in our lab on other computers. This issue seems to be quite specific to my laptop. I have just not been able to figure out what the issue is with my laptop so I would appreciate any insights you might have on this.

Thank you

Jae-Hyun Kim 
https://jahyki.github.io/
Department of Linguistics
Macquarie University, Sydney, Australia

**Comment by jahyki** [comment]
Also just adding the screenshot of the error on MATLAB if it helps at all. 
Thanks again.

<img width="1489" alt="Screenshot 2024-05-05 at 2 14 44 pm" src="https://github.com/WeirongChen/DeepEdge/assets/98289234/22d83cc7-19fe-41f2-8dc8-f28dd0acf101">

**Comment by WeirongChen** [comment]
Dear Jae-Hyun, 
Thank you for trying DeepEdge and reporting issue.
Currently 'make_snake' doesn't support Apple Silicon M-series CPU.   For now, please use Intel-based platform to run DeepEdge.

**Comment by jahyki** [comment]
Thanks.
That makes a lot of sense.
Much appreciated.
